title: How to be an Author!
author: Rcaples1125
email: your-email@domain.com
description: > Welcome to How to be an author! Do you have a creative mind? Wanna get your ideas
out on paper? Anyone can be an author is you have the right mind set. Come with me and explore how 
creative you can be.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
