title: Blog Creation!
author: Rcaples1125
email: your-email@domain.com
description: > Welcome to Blog Creation! In this blog you will learn how to create a blog.
This will help you learn a new skill. 

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
